name: Swift CI

on:
  pull_request:
    paths:
      - ./**.swift
      - .github/workflows/swift-ci.yaml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: swift:6.0.1-noble
    timeout-minutes: 5
    steps:
      - run: swift --version

      - run: swift format lint -r .

