name: Swift CI

on:
  pull_request:
    paths:
      - ./**.swift
      - .github/workflows/swift-ci.yaml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: NeedleInAJayStack/setup-swift@feat/swift-6
        with:
          swift-version: "6.0"
      - run: swift --version

      - run: swift format lint -r .

